general {
    colors = true
    interval = 5
}

order += "volume master"
order += "ipv6"
order += "wireless _first_"
order += "ethernet _first_"
order += "battery all"
order += "disk /"
order += "load"
order += "memory"
order += "tztime local"

volume master {
    format        = "♪ %volume"
    format_muted  = "♪ muted"
    device        = "pulse"
}

battery all {
    format      = "%status %percentage %remaining"
    format_down = "no battery"
    status_chr  = "CHR"
    status_bat  = "BAT"
    status_full = "FULL"
    low_threshold = 10
    path = "/sys/class/power_supply/BAT%d/uevent"
}

wireless _first_ {
    format_up   = "W: (%quality at %essid) %ip"
    format_down = "W: down"
}

ethernet _first_ {
    format_up   = "E: %ip (speed: %speed)"
    format_down = "E: down"
}

disk "/" {
    format = "%free"
}

load {
    format = "%1min"
}

memory {
    format           = "%used | %available"
    threshold_degraded = "1G"
    format_degraded  = "MEMORY < %available"
}

tztime local {
    format = "%Y-%m-%d %H:%M:%S"
}
